spring:
  application:
    name: iToken-admin
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8084


#监控服务的状态（health,健康  info 日志） 也可以写* 代表监控所有
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

