spring:
  application:
    name: iToken-eureka

server:
  port: 8762

eureka:
  instance:
    hostname: 192.168.226.129
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.226.129:${serve.port}/eureka/,http://192.168.226.129:${serve.port}/eureka/,http://192.168.226.129:${serve.port}/eureka/



#监控服务的状态（health,健康  info 日志） 也可以写* 代表监控所有
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info