spring:
  application:
    name: iToken-Zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false