spring:
  application:
    name: iToken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/iToken-wzq/iToken-config.git
          search-paths: respo
          username: MyWXF
          password: Wzq123456@

  #被zipkin追踪加的配置
  zipkin:
    base-url: http://192.168.226.129:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.226.129:8762/eureka/


#监控服务的状态（health,健康  info 日志） 也可以写* 代表监控所有
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info