spring:
  application:
    name: iToken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/iToken-wzq/iToken-config.git
          search-paths: respo
          username: MyWXF
          password: Wzq123456@

  #被zipkin追踪加的配置
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/